eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: zuul-server
  redis:
    host: 176.122.133.13
    port: 6379
    password: william687

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  routes:
    aaa:
      path: /mychannel/**
      serviceId: CHANNEL-SERVER
    bbb:
        path: /user/**
        serviceId: AUTH-SERVER


  sensitive-headers :
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
   enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000