eureka:
  client:
    service-url:
      defaultZone: http:// 192.168.1.111:8761/eureka/
#    defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761